
package ui;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.MessageFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.lang.Math;
import javax.swing.JDialog;
import java.util.Random;

public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    
     Double bHeight=0.0;
     ArrayList<String> itemName = new ArrayList<>();
    ArrayList<Integer> quantity = new ArrayList<>();
    ArrayList<Double> itemPrice = new ArrayList<>();
    ArrayList<Double> subtotal = new ArrayList<>();
    
    public Home() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        // Maximize the JFrame to occupy the whole screen
        setExtendedState(JFrame.MAXIMIZED_BOTH);
          startTimerToUpdateDateLabel();
     
    }
      private void updateDateLabel() {
        LocalDateTime now = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        String formattedDateTime = now.format(formatter);
        date.setText("Date/Time: " + formattedDateTime);
    }
      private void startTimerToUpdateDateLabel() {
        Timer timer = new Timer(1000, (ActionEvent e) -> {
            updateDateLabel();
        });
        timer.start();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    //
        public void ItemCost()
    {
     double sum = 0;
    itemName.clear();
    quantity.clear();
    itemPrice.clear();
    subtotal.clear();

    for (int i = 0; i < jtable1.getRowCount(); i++) {
        // Ensure proper parsing and handling of potential null or incorrect values
        String item = jtable1.getValueAt(i, 1) != null ? jtable1.getValueAt(i, 1).toString() : "";
        itemName.add(item);

        int qty = 0;
        try {
            qty = Integer.parseInt(jtable1.getValueAt(i, 0).toString());
        } catch (NumberFormatException e) {
            e.printStackTrace();
        }
        quantity.add(qty);

        double price = 0.0;
        try {
            price = Double.parseDouble(jtable1.getValueAt(i, 2).toString());
        } catch (NumberFormatException e) {
            e.printStackTrace();
        }
        itemPrice.add(price);

        double rowSubtotal = qty * price;
        subtotal.add(rowSubtotal);
        sum += rowSubtotal;
    }

    SubTotal.setText(String.format("%.2f", sum));
    double ctotal = sum;

    double tax = (ctotal * 12) / 100;
    
    String taxTotal = String.format("₱ %.2f", tax);
    Tax.setText(taxTotal);

    String subTotal = String.format("₱ %.2f", ctotal);
    SubTotal.setText(subTotal);

    double hatdog = ctotal + tax;
    double aTotall = Math.round(hatdog * 100.0) / 100.0;
    if (aTotall - (int) aTotall >= 0.995) {
            aTotall = Math.ceil(aTotall);  // Round up using Math.ceil() if necessary
        }
    String mytotal = String.format("₱ %.2f", aTotall);
    Total.setText(mytotal);
    txtupTotal.setText(mytotal);

    String Barcode = String.format("%.2f", ctotal + tax);
    barcode.setText(Barcode);
    }
    
    // CHANGE
    
    public void Change()
    {
       if (tenders.getSelectedItem().equals("Cash")) {
    double sum = 0;
    double cash = Double.parseDouble(cashDisplay.getText());

    for (int i = 0; i < jtable1.getRowCount(); i++) {
        sum += Double.parseDouble(jtable1.getValueAt(i, 2).toString());
    }

    double newtax = (sum * 12) / 100;
    double change = cash - (sum + newtax);

    String myChange = String.format("₱ %.2f", change);
    changeDisplay.setText(myChange);
} 
     else {
           double sum = 0;
   double cash = Double.parseDouble(cashDisplay.getText());

    for (int i = 0; i < jtable1.getRowCount(); i++) {
        sum += Double.parseDouble(jtable1.getValueAt(i, 2).toString());
    }

  
    double change = sum * 0;

    String myChange = String.format("₱ %.2f", change);
    changeDisplay.setText(myChange);
}
         
    }

    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jbutton2 = new javax.swing.JButton();
        jbutton3 = new javax.swing.JButton();
        jbutton1 = new javax.swing.JButton();
        jbutton5 = new javax.swing.JButton();
        jbutton6 = new javax.swing.JButton();
        jbutton4 = new javax.swing.JButton();
        jbutton8 = new javax.swing.JButton();
        jbutton9 = new javax.swing.JButton();
        jbutton7 = new javax.swing.JButton();
        jbuttondot = new javax.swing.JButton();
        jbuttonclear = new javax.swing.JButton();
        jbutton0 = new javax.swing.JButton();
        barcode = new javax.swing.JTextField();
        jbuttonconfirm = new javax.swing.JButton();
        printbutton = new javax.swing.JButton();
        voidbutton = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        caramelM = new javax.swing.JButton();
        americano = new javax.swing.JButton();
        wmocha = new javax.swing.JButton();
        mocha = new javax.swing.JButton();
        cappuccino = new javax.swing.JButton();
        mango = new javax.swing.JButton();
        passion = new javax.swing.JButton();
        strawb = new javax.swing.JButton();
        melon = new javax.swing.JButton();
        cranb = new javax.swing.JButton();
        gapple = new javax.swing.JButton();
        apple = new javax.swing.JButton();
        orange = new javax.swing.JButton();
        strawbs = new javax.swing.JButton();
        lemon = new javax.swing.JButton();
        clatte = new javax.swing.JButton();
        matchal = new javax.swing.JButton();
        saltedC = new javax.swing.JButton();
        vlatte = new javax.swing.JButton();
        dmatcha = new javax.swing.JButton();
        bbck = new javax.swing.JButton();
        wmochaf = new javax.swing.JButton();
        lvck = new javax.swing.JButton();
        upsize = new javax.swing.JButton();
        mochaf = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        SubTotal = new javax.swing.JTextField();
        Tax = new javax.swing.JTextField();
        Total = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tenders = new javax.swing.JComboBox<>();
        cashDisplay = new javax.swing.JTextField();
        cashLabel = new javax.swing.JLabel();
        changeDisplay = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtupTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        jButton13.setText("jButton7");

        jButton14.setText("jButton7");

        jButton15.setText("jButton7");

        jButton16.setText("jButton7");

        jButton17.setText("jButton7");

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setPreferredSize(new java.awt.Dimension(300, 510));

        jbutton2.setBackground(new java.awt.Color(0, 0, 0));
        jbutton2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbutton2.setForeground(new java.awt.Color(255, 255, 255));
        jbutton2.setText("2");
        jbutton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jbutton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton2ActionPerformed(evt);
            }
        });

        jbutton3.setBackground(new java.awt.Color(0, 0, 0));
        jbutton3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbutton3.setForeground(new java.awt.Color(255, 255, 255));
        jbutton3.setText("3");
        jbutton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jbutton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbutton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton3ActionPerformed(evt);
            }
        });

        jbutton1.setBackground(new java.awt.Color(0, 0, 0));
        jbutton1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbutton1.setForeground(new java.awt.Color(255, 255, 255));
        jbutton1.setText("1");
        jbutton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jbutton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton1ActionPerformed(evt);
            }
        });

        jbutton5.setBackground(new java.awt.Color(0, 0, 0));
        jbutton5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbutton5.setForeground(new java.awt.Color(255, 255, 255));
        jbutton5.setText("5");
        jbutton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jbutton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbutton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton5ActionPerformed(evt);
            }
        });

        jbutton6.setBackground(new java.awt.Color(0, 0, 0));
        jbutton6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbutton6.setForeground(new java.awt.Color(255, 255, 255));
        jbutton6.setText("6");
        jbutton6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jbutton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbutton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton6ActionPerformed(evt);
            }
        });

        jbutton4.setBackground(new java.awt.Color(0, 0, 0));
        jbutton4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbutton4.setForeground(new java.awt.Color(255, 255, 255));
        jbutton4.setText("4");
        jbutton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jbutton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbutton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton4ActionPerformed(evt);
            }
        });

        jbutton8.setBackground(new java.awt.Color(0, 0, 0));
        jbutton8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbutton8.setForeground(new java.awt.Color(255, 255, 255));
        jbutton8.setText("8");
        jbutton8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jbutton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbutton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton8ActionPerformed(evt);
            }
        });

        jbutton9.setBackground(new java.awt.Color(0, 0, 0));
        jbutton9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbutton9.setForeground(new java.awt.Color(255, 255, 255));
        jbutton9.setText("9");
        jbutton9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jbutton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbutton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton9ActionPerformed(evt);
            }
        });

        jbutton7.setBackground(new java.awt.Color(0, 0, 0));
        jbutton7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbutton7.setForeground(new java.awt.Color(255, 255, 255));
        jbutton7.setText("7");
        jbutton7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jbutton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbutton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton7ActionPerformed(evt);
            }
        });

        jbuttondot.setBackground(new java.awt.Color(0, 0, 0));
        jbuttondot.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbuttondot.setForeground(new java.awt.Color(255, 255, 255));
        jbuttondot.setText(".");
        jbuttondot.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jbuttondot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuttondot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttondotActionPerformed(evt);
            }
        });

        jbuttonclear.setBackground(new java.awt.Color(204, 0, 0));
        jbuttonclear.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbuttonclear.setForeground(new java.awt.Color(255, 255, 255));
        jbuttonclear.setText("C");
        jbuttonclear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jbuttonclear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuttonclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonclearActionPerformed(evt);
            }
        });

        jbutton0.setBackground(new java.awt.Color(0, 0, 0));
        jbutton0.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbutton0.setForeground(new java.awt.Color(255, 255, 255));
        jbutton0.setText("0");
        jbutton0.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jbutton0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbutton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton0ActionPerformed(evt);
            }
        });

        barcode.setEditable(false);
        barcode.setFont(new java.awt.Font("IDAutomationHC39M", 0, 24)); // NOI18N
        barcode.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jbuttonconfirm.setBackground(new java.awt.Color(0, 204, 51));
        jbuttonconfirm.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbuttonconfirm.setForeground(new java.awt.Color(255, 255, 255));
        jbuttonconfirm.setText("PAY");
        jbuttonconfirm.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jbuttonconfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuttonconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonconfirmActionPerformed(evt);
            }
        });

        printbutton.setBackground(new java.awt.Color(51, 51, 255));
        printbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        printbutton.setForeground(new java.awt.Color(255, 255, 255));
        printbutton.setText("Print");
        printbutton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        printbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        printbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbuttonActionPerformed(evt);
            }
        });

        voidbutton.setBackground(new java.awt.Color(51, 51, 255));
        voidbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        voidbutton.setForeground(new java.awt.Color(255, 255, 255));
        voidbutton.setText("Void");
        voidbutton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        voidbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voidbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voidbuttonActionPerformed(evt);
            }
        });

        reset.setBackground(new java.awt.Color(51, 51, 255));
        reset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setText("Reset");
        reset.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(204, 0, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Exit");
        jButton6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(printbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16)
                        .addComponent(voidbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jbuttonconfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(barcode)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jbutton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jbutton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jbutton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jbutton5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jbutton6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jbutton7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jbutton8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jbutton9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jbutton0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jbuttondot, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jbuttonclear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbutton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbutton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbutton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbutton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbutton6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbutton7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbutton8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbutton9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbutton0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbuttondot, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbuttonclear, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jbuttonconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voidbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Qty", "Item", "Amount", "Total"
            }
        ));
        jtable1.setGridColor(new java.awt.Color(255, 255, 255));
        jtable1.setRowHeight(40);
        jtable1.setRowMargin(20);
        jtable1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jtable1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        caramelM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        caramelM.setText("CF1");
        caramelM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        caramelM.setPreferredSize(new java.awt.Dimension(100, 100));
        caramelM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caramelMActionPerformed(evt);
            }
        });

        americano.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        americano.setText("CF3");
        americano.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        americano.setPreferredSize(new java.awt.Dimension(100, 100));
        americano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                americanoActionPerformed(evt);
            }
        });

        wmocha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        wmocha.setText("CF4");
        wmocha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        wmocha.setPreferredSize(new java.awt.Dimension(100, 100));
        wmocha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wmochaActionPerformed(evt);
            }
        });

        mocha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mocha.setText("CF5");
        mocha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mocha.setPreferredSize(new java.awt.Dimension(100, 100));
        mocha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mochaActionPerformed(evt);
            }
        });

        cappuccino.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cappuccino.setText("CF2");
        cappuccino.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cappuccino.setPreferredSize(new java.awt.Dimension(100, 100));
        cappuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cappuccinoActionPerformed(evt);
            }
        });

        mango.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mango.setText("FT3");
        mango.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mango.setPreferredSize(new java.awt.Dimension(100, 100));
        mango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mangoActionPerformed(evt);
            }
        });

        passion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passion.setText("FT1");
        passion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        passion.setPreferredSize(new java.awt.Dimension(100, 100));
        passion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passionActionPerformed(evt);
            }
        });

        strawb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        strawb.setText("FT4");
        strawb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        strawb.setPreferredSize(new java.awt.Dimension(100, 100));
        strawb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strawbActionPerformed(evt);
            }
        });

        melon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        melon.setText("FT5");
        melon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        melon.setPreferredSize(new java.awt.Dimension(100, 100));
        melon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                melonActionPerformed(evt);
            }
        });

        cranb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cranb.setText("FT2");
        cranb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cranb.setPreferredSize(new java.awt.Dimension(100, 100));
        cranb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cranbActionPerformed(evt);
            }
        });

        gapple.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gapple.setText("FS3");
        gapple.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gapple.setPreferredSize(new java.awt.Dimension(100, 100));
        gapple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gappleActionPerformed(evt);
            }
        });

        apple.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        apple.setText("FS1");
        apple.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        apple.setPreferredSize(new java.awt.Dimension(100, 100));
        apple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appleActionPerformed(evt);
            }
        });

        orange.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        orange.setText("FS4");
        orange.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        orange.setPreferredSize(new java.awt.Dimension(100, 100));
        orange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orangeActionPerformed(evt);
            }
        });

        strawbs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        strawbs.setText("FS5");
        strawbs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        strawbs.setPreferredSize(new java.awt.Dimension(100, 100));
        strawbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strawbsActionPerformed(evt);
            }
        });

        lemon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lemon.setText("FS2");
        lemon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lemon.setPreferredSize(new java.awt.Dimension(100, 100));
        lemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lemonActionPerformed(evt);
            }
        });

        clatte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clatte.setText("SPD3");
        clatte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clatte.setPreferredSize(new java.awt.Dimension(100, 100));
        clatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clatteActionPerformed(evt);
            }
        });

        matchal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        matchal.setText("SPD1");
        matchal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        matchal.setPreferredSize(new java.awt.Dimension(100, 100));
        matchal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matchalActionPerformed(evt);
            }
        });

        saltedC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saltedC.setText("SPD4");
        saltedC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saltedC.setPreferredSize(new java.awt.Dimension(100, 100));
        saltedC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saltedCActionPerformed(evt);
            }
        });

        vlatte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vlatte.setText("SPD5");
        vlatte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vlatte.setPreferredSize(new java.awt.Dimension(100, 100));
        vlatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vlatteActionPerformed(evt);
            }
        });

        dmatcha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dmatcha.setText("SPD2");
        dmatcha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dmatcha.setPreferredSize(new java.awt.Dimension(100, 100));
        dmatcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dmatchaActionPerformed(evt);
            }
        });

        bbck.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bbck.setText("CK1");
        bbck.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bbck.setPreferredSize(new java.awt.Dimension(100, 100));
        bbck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbckActionPerformed(evt);
            }
        });

        wmochaf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        wmochaf.setText("FC1");
        wmochaf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        wmochaf.setPreferredSize(new java.awt.Dimension(100, 100));
        wmochaf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wmochafActionPerformed(evt);
            }
        });

        lvck.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lvck.setText("CK2");
        lvck.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lvck.setPreferredSize(new java.awt.Dimension(100, 100));
        lvck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lvckActionPerformed(evt);
            }
        });

        upsize.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        upsize.setText("UPSIZE");
        upsize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        upsize.setPreferredSize(new java.awt.Dimension(100, 100));
        upsize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upsizeActionPerformed(evt);
            }
        });

        mochaf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mochaf.setText("FC2");
        mochaf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mochaf.setPreferredSize(new java.awt.Dimension(100, 100));
        mochaf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mochafActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(wmochaf, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(mochaf, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(bbck, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lvck, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(upsize, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(caramelM, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(cappuccino, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(americano, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(wmocha, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(mocha, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(passion, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(cranb, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(mango, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(strawb, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(melon, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(apple, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lemon, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(gapple, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(orange, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(strawbs, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(matchal, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(dmatcha, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(clatte, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(saltedC, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(vlatte, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)))
                .addGap(82, 82, 82))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cappuccino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(americano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(wmocha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mocha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(caramelM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cranb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mango, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(strawb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(melon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lemon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gapple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(strawbs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matchal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dmatcha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clatte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saltedC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vlatte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wmochaf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mochaf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bbck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lvck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(upsize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60))
        );

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));

        SubTotal.setEditable(false);
        SubTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        Tax.setEditable(false);
        Tax.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Tax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaxActionPerformed(evt);
            }
        });

        Total.setEditable(false);
        Total.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Subtotal");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tax");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Change");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Payment");

        tenders.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tenders.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "CC/DC", "QRPH" }));
        tenders.setAutoscrolls(true);
        tenders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tendersActionPerformed(evt);
            }
        });

        cashDisplay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        cashLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cashLabel.setForeground(new java.awt.Color(255, 255, 255));
        cashLabel.setText("Cash");

        changeDisplay.setEditable(false);
        changeDisplay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        changeDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeDisplayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel4)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(Tax)
                    .addComponent(Total))
                .addGap(146, 146, 146)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cashLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tenders, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cashDisplay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tenders, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cashLabel)
                            .addComponent(cashDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(changeDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tax, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        txtupTotal.setEditable(false);
        txtupTotal.setBackground(new java.awt.Color(0, 0, 0));
        txtupTotal.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtupTotal.setForeground(new java.awt.Color(255, 255, 255));
        txtupTotal.setBorder(null);
        txtupTotal.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtupTotal.setEnabled(false);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("This Transaction:");

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Bean There, Done That");

        date.setBackground(new java.awt.Color(0, 0, 0));
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(51, 51, 51)
                .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(262, 262, 262)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(465, 465, 465)
                .addComponent(txtupTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtupTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(date))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addGap(0, 0, 0)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 933, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void printbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbuttonActionPerformed
     /* MessageFormat header = new MessageFormat("Bean There, Done That");
      MessageFormat footer = new MessageFormat("Page {0, number, integer}");
        
        try
        {
            jtable1.print (JTable.PrintMode.NORMAL,header,footer);
        }
        
        catch(java.awt.print.PrinterException e)
        {
            System.err.format("No Printer found", e.getMessage());
        }*/
     JOptionPane printingDialog = new JOptionPane("Printing in progress. Please wait...", JOptionPane.INFORMATION_MESSAGE);
    JDialog dialog = printingDialog.createDialog(this, "Printing");

    // Create a Timer to close the dialog after a delay
    Timer timer = new Timer(2000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            dialog.dispose(); // Close the dialog
        }
    });
    timer.setRepeats(false); // Ensure the timer only runs once
    timer.start(); // Start the timer

    dialog.setVisible(true); 
    
      ItemCost();
    Change();

    // Perform the print job
    bHeight = Double.valueOf(itemName.size());
    PrinterJob pj = PrinterJob.getPrinterJob();        
    pj.setPrintable(new BillPrintable(), getPageFormat(pj));
    try {
        pj.print();
         JOptionPane.showMessageDialog(this, "Printing completed successfully.", "Printing", JOptionPane.INFORMATION_MESSAGE);
         reset2();
          
    } catch (PrinterException ex) {
        ex.printStackTrace();
           JOptionPane.showMessageDialog(this, "Printing failed: " + ex.getMessage(), "Printing Error", JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_printbuttonActionPerformed

  public PageFormat getPageFormat(PrinterJob pj) {
    PageFormat pf = pj.defaultPage();
    Paper paper = pf.getPaper();

    double bodyHeight = bHeight;  
    double headerHeight = 5.0;                  
    double footerHeight = 5.0; 

    // Width of the paper in centimeters (for 80mm wide thermal paper)
    double widthCm = 8.0; // 8.0 cm = 80 mm
    // Total height in centimeters
    double totalHeightCm = headerHeight + bodyHeight + footerHeight;

    // Convert width and height to points
    double widthPoints = cm_to_pp(widthCm);
    double heightPoints = cm_to_pp(totalHeightCm);

    // Set the size and imageable area of the paper
    paper.setSize(widthPoints, heightPoints);
    paper.setImageableArea(0, 10, widthPoints, heightPoints - cm_to_pp(1));  

    pf.setOrientation(PageFormat.PORTRAIT);  
    pf.setPaper(paper);    

    return pf;
}

// Helper method to convert centimeters to points
protected static double cm_to_pp(double cm) {
    return cm * 28.3464567; // 1 cm = 28.3464567 points
}
   
    
    
 
 
protected static double toPPI(double inch)
    {            
	        return inch * 72d;            
    }
  public class BillPrintable implements Printable {
    private int getCenteredPosition(String text, FontMetrics metrics, double pageWidth) {
        int textWidth = metrics.stringWidth(text);
        return (int) ((pageWidth - textWidth) / 2);
    }

    @Override
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
        if (pageIndex != 0) return NO_SUCH_PAGE;

        Graphics2D g2d = (Graphics2D) graphics;
        double width = pageFormat.getImageableWidth();
        g2d.translate((int) pageFormat.getImageableX(), (int) pageFormat.getImageableY());

        Font font = new Font("Monospaced", Font.PLAIN, 9);
        g2d.setFont(font);
        FontMetrics metrics = g2d.getFontMetrics(font);

        try {
            int y = 20;
            int yShift = 10;
            int headerRectHeight = 15;

            String[] lines = {
                "                                     ",
                "        Bean There, Done That        ",
                "                                     ",
                "   Brgy. Tagapo, Sta. Rosa, Laguna   ",
                " VAT Registered TIN: 000-000-000-000 ",
                "    ",
                "       ",
                "-------------------------------------",
                "  Qty        Item Name         Price ",
                "-------------------------------------"
            };

            for (String line : lines) {
                g2d.drawString(line, getCenteredPosition(line, metrics, width), y);
                y += yShift;
            }
            

            Map<String, Integer> itemQuantities = new HashMap<>();

            // Aggregate quantities
            for (int s = 0; s < itemName.size(); s++) {
                String name = itemName.get(s);
                int quantityValue = quantity.get(s);
                double aPrice = itemPrice.get(s);
                double priceWithTax = aPrice * (1 + 0.12); // 12% tax added

                if (itemQuantities.containsKey(name)) {
                    itemQuantities.put(name, itemQuantities.get(name) + quantityValue);
                } else {
                    itemQuantities.put(name, quantityValue);
                }

                String itemLine = " " + quantityValue + "      " + name + "         " + String.format("%.2f", priceWithTax);
                g2d.drawString(itemLine, getCenteredPosition(itemLine, metrics, width), y);
                y += yShift;
            }

            String[] footerLines = {
                "-------------------------------------",
                " Total amount:          " + txtupTotal.getText() + "   ",
                "-------------------------------------",
                " Payment   :            " + "₱ " + cashDisplay.getText() + "   ",
                "-------------------------------------",
                " Change   :             " + changeDisplay.getText() + "   ",
                "                                     ",
                ""+ date.getText() + "",
                "*************************************",
                "       THANK YOU COME AGAIN          ",
                "*************************************",
                "       Bean There, Done That         ",
                "                                     "
            };

            for (String line : footerLines) {
                g2d.drawString(line, getCenteredPosition(line, metrics, width), y);
                y += yShift;
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        return PAGE_EXISTS;
    }
}

    private void voidbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voidbuttonActionPerformed
          DefaultTableModel model = (DefaultTableModel) jtable1.getModel();

int selectedRow = jtable1.getSelectedRow();
if (selectedRow >= 0) {
    // Display confirmation dialog
    int option = JOptionPane.showConfirmDialog(this, "Are you sure you want to remove this item?", "Confirm Removal", JOptionPane.YES_NO_OPTION);
    
    if (option == JOptionPane.YES_OPTION) {
        // Remove the selected row
        model.removeRow(selectedRow);

        // Recalculate item costs
        ItemCost();

        // Check tender selection and update accordingly
        if (tenders.getSelectedItem().equals("Cash")) {
            Change(); // Calculate change if payment method is cash
        } else {
            changeDisplay.setText("");
            cashDisplay.setText("");
        }
    }
} else {
    // If no row is selected, show a dialog
    JOptionPane.showMessageDialog(this, "Please select an item to remove.", "No Item Selected", JOptionPane.INFORMATION_MESSAGE);
}

    }//GEN-LAST:event_voidbuttonActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
       int option = JOptionPane.showConfirmDialog(this, "Are you sure you want to reset?", "Confirm Reset", JOptionPane.YES_NO_OPTION);

    if (option == JOptionPane.YES_OPTION) {
        // User confirmed, proceed with reset
        DefaultTableModel model = (DefaultTableModel) jtable1.getModel();
        model.setRowCount(0);
        changeDisplay.setText("");
        cashDisplay.setText("");
        barcode.setText("");
        SubTotal.setText("");
        Tax.setText("");
        Total.setText("");
        txtupTotal.setText("");
    }
    }//GEN-LAST:event_resetActionPerformed
private JFrame frame;
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
     frame = new JFrame("Exit");
    if (JOptionPane.showConfirmDialog(frame, "Do you want to exit?", "Exit Confirmation",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) 
    {
        LogIn login = new LogIn();
    login.setVisible(true);
    this.dispose();
    }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void tendersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tendersActionPerformed
          String selected = (String) tenders.getSelectedItem();
        if ("Cash".equals(selected)) {
            cashLabel.setText("Cash");
        } else {
            cashLabel.setText("Code");
        }
    }//GEN-LAST:event_tendersActionPerformed

     
 public void reset2(){
      DefaultTableModel model = (DefaultTableModel) jtable1.getModel();
        model.setRowCount(0);
        changeDisplay.setText("");
        cashDisplay.setText("");
        barcode.setText("");
        SubTotal.setText("");
        Tax.setText("");
        Total.setText("");
        txtupTotal.setText("");
 }
 
  
    private void jbuttonconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonconfirmActionPerformed
      
         if (tenders.getSelectedItem().equals("Cash")) {
        // Existing logic for handling cash input
        String cashInput = cashDisplay.getText().trim();
        String totalInput = Total.getText().trim();

        // Remove currency symbol and any formatting
        String cleanCashInput = cashInput.replaceAll("[₱\\s]", "");
        String cleanTotalInput = totalInput.replaceAll("[₱\\s]", "");

        // Validate the cash input
        if (!cleanCashInput.isEmpty() && !cleanTotalInput.isEmpty()) {
            try {
                double cashAmount = Double.parseDouble(cleanCashInput);
                double totalAmount = Double.parseDouble(cleanTotalInput);

                if (cashAmount < totalAmount) {
                    JOptionPane.showMessageDialog(this, "Cash amount must be equal to or greater than Total.", "Insufficient Cash", JOptionPane.ERROR_MESSAGE);
                } else {
                    // Proceed with your logic when cash amount is sufficient
                    Change(); // Call your Change() method or perform required actions
                    String formattedCashAmount = String.format("%.2f", cashAmount);
                    cashDisplay.setText(formattedCashAmount);

                    // Show confirmation dialog
                    int result = JOptionPane.showConfirmDialog(this, "CONFIRM PAYMENT?", "Payment", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);

                    if (result == JOptionPane.YES_OPTION) {
                        printbuttonActionPerformed(evt); // Call the print button action
                    }
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid input. Please enter valid numeric values.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Select item/s and enter the cash amount.", "Missing Input", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        changeDisplay.setText("0.00");
         cashDisplay.setText("0000");
        // Set changeDisplay to "0.00"

// Generate a random number for cashDisplay
Random rand = new Random();
double randomCash = 1000 + (5000 - 1000) * rand.nextDouble(); // Generate a random number between 1000 and 5000
String formattedCashAmount = String.format("%.2f", randomCash);
changeDisplay.setForeground(Color.BLACK);
// Validate the generated random number is not null or empty
if (formattedCashAmount != null && !formattedCashAmount.isEmpty()) {
    cashDisplay.setText("0000"); // Set the generated random number in cashDisplay
   

    // Show confirmation dialog
    int result = JOptionPane.showConfirmDialog(this, "CONFIRM PAYMENT?", "Payment", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);

    if (result == JOptionPane.YES_OPTION) {
        printbuttonActionPerformed(evt); // Call the print button action
    } 
} else {
    JOptionPane.showMessageDialog(this, "Put a code.", "Error", JOptionPane.ERROR_MESSAGE);
}
         }
    }//GEN-LAST:event_jbuttonconfirmActionPerformed

    private void jbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton1ActionPerformed
      String EnterNum = cashDisplay.getText();
      
      if (EnterNum == "")
      {
          cashDisplay.setText(jbutton1.getText());
        
      }
      else
      {
          EnterNum = cashDisplay.getText() + jbutton1.getText();
          cashDisplay.setText(EnterNum);
         
      }

    }//GEN-LAST:event_jbutton1ActionPerformed

    private void saltedCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saltedCActionPerformed
       double Price = 142.86;
        double cPrice = ((Price * 12)/100) + Price;
        DefaultTableModel model = (DefaultTableModel) jtable1.getModel();
        model.addRow(new Object[] {"1", "Salted C  ", Price, String.format("%.2f", cPrice)});
        ItemCost();

    }//GEN-LAST:event_saltedCActionPerformed

    private void clatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clatteActionPerformed
         double Price = 142.86;
        double cPrice = ((Price * 12)/100) + Price;
        DefaultTableModel model = (DefaultTableModel) jtable1.getModel();
        model.addRow(new Object[] {"1", "CocoaLatte", Price, String.format("%.2f", cPrice)});
        ItemCost();
    }//GEN-LAST:event_clatteActionPerformed

    private void jbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton2ActionPerformed
       String EnterNum = cashDisplay.getText();
      
      if (EnterNum == "")
      {
          cashDisplay.setText(jbutton2.getText());
      }
      else
      {
          EnterNum = cashDisplay.getText() + jbutton2.getText();
          cashDisplay.setText(EnterNum);
      }
    }//GEN-LAST:event_jbutton2ActionPerformed

    private void jbutton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton3ActionPerformed
      String EnterNum = cashDisplay.getText();
      
      if (EnterNum == "")
      {
          cashDisplay.setText(jbutton3.getText());
      }
      else
      {
          EnterNum = cashDisplay.getText() + jbutton3.getText();
          cashDisplay.setText(EnterNum);
      }
    }//GEN-LAST:event_jbutton3ActionPerformed

    private void jbutton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton4ActionPerformed
        String EnterNum = cashDisplay.getText();
      
      if (EnterNum == "")
      {
          cashDisplay.setText(jbutton4.getText());
      }
      else
      {
          EnterNum = cashDisplay.getText() + jbutton4.getText();
          cashDisplay.setText(EnterNum);
      }
    }//GEN-LAST:event_jbutton4ActionPerformed

    private void jbutton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton5ActionPerformed
         String EnterNum = cashDisplay.getText();
      
      if (EnterNum == "")
      {
          cashDisplay.setText(jbutton5.getText());
      }
      else
      {
          EnterNum = cashDisplay.getText() + jbutton5.getText();
          cashDisplay.setText(EnterNum);
      }
    }//GEN-LAST:event_jbutton5ActionPerformed

    private void jbutton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton6ActionPerformed
         String EnterNum = cashDisplay.getText();
      
      if (EnterNum == "")
      {
          cashDisplay.setText(jbutton6.getText());
      }
      else
      {
          EnterNum = cashDisplay.getText() + jbutton6.getText();
          cashDisplay.setText(EnterNum);
      }
    }//GEN-LAST:event_jbutton6ActionPerformed

    private void jbutton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton7ActionPerformed
        String EnterNum = cashDisplay.getText();
      
      if (EnterNum == "")
      {
          cashDisplay.setText(jbutton7.getText());
      }
      else
      {
          EnterNum = cashDisplay.getText() + jbutton7.getText();
          cashDisplay.setText(EnterNum);
      }
    }//GEN-LAST:event_jbutton7ActionPerformed

    private void jbutton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton8ActionPerformed
        String EnterNum = cashDisplay.getText();
      
      if (EnterNum == "")
      {
          cashDisplay.setText(jbutton8.getText());
      }
      else
      {
          EnterNum = cashDisplay.getText() + jbutton8.getText();
          cashDisplay.setText(EnterNum);
      }
    }//GEN-LAST:event_jbutton8ActionPerformed

    private void jbutton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton9ActionPerformed
         String EnterNum = cashDisplay.getText();
      
      if (EnterNum == "")
      {
          cashDisplay.setText(jbutton9.getText());
      }
      else
      {
          EnterNum = cashDisplay.getText() + jbutton9.getText();
          cashDisplay.setText(EnterNum);
      }
    }//GEN-LAST:event_jbutton9ActionPerformed

    private void jbutton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton0ActionPerformed
         String EnterNum = cashDisplay.getText();
      
      if (EnterNum == "")
      {
          cashDisplay.setText(jbutton0.getText());
      }
      else
      {
          EnterNum = cashDisplay.getText() + jbutton0.getText();
          cashDisplay.setText(EnterNum);
      }
    }//GEN-LAST:event_jbutton0ActionPerformed

    private void jbuttondotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttondotActionPerformed
           if(! cashDisplay.getText().contains(".")){
            cashDisplay.setText(cashDisplay.getText() + jbuttondot.getText());
        }

    }//GEN-LAST:event_jbuttondotActionPerformed

    private void jbuttonclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonclearActionPerformed
            
       cashDisplay.setText("");
       changeDisplay.setText("");

    }//GEN-LAST:event_jbuttonclearActionPerformed

    private void caramelMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caramelMActionPerformed
              double Price = 133.93;
        double cPrice = ((Price * 12)/100) + Price;
        DefaultTableModel model = (DefaultTableModel) jtable1.getModel();
        model.addRow(new Object[] {"1", "Caramel M ", Price, String.format("%.2f", cPrice)});
        ItemCost();

    }//GEN-LAST:event_caramelMActionPerformed

    private void cappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cappuccinoActionPerformed
               double Price = 133.93;
        double cPrice = ((Price * 12)/100) + Price;
        DefaultTableModel model = (DefaultTableModel) jtable1.getModel();
        model.addRow(new Object[] {"1", "Cappuccino", Price, String.format("%.2f", cPrice)});
        ItemCost();

    }//GEN-LAST:event_cappuccinoActionPerformed

    private void americanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_americanoActionPerformed
              double Price = 107.14;
        double cPrice = ((Price * 12)/100) + Price;
        DefaultTableModel model = (DefaultTableModel) jtable1.getModel();
        model.addRow(new Object[] {"1", "Americano ", Price, String.format("%.2f", cPrice)});
        ItemCost();

    }//GEN-LAST:event_americanoActionPerformed

    private void wmochaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wmochaActionPerformed
      double Price = 133.93;
        double cPrice = ((Price * 12)/100) + Price;
        DefaultTableModel model = (DefaultTableModel) jtable1.getModel();
        model.addRow(new Object[] {"1", "W Mocha   ", Price, String.format("%.2f", cPrice)});
        ItemCost();

    }//GEN-LAST:event_wmochaActionPerformed

    private void mochaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mochaActionPerformed
              double Price = 133.93;
        double cPrice = ((Price * 12)/100) + Price;
        DefaultTableModel model = (DefaultTableModel) jtable1.getModel();
        model.addRow(new Object[] {"1", "Mocha     ", Price, String.format("%.2f", cPrice)});
        ItemCost();

    }//GEN-LAST:event_mochaActionPerformed

    private void passionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passionActionPerformed
       double Price = 107.14;
        double cPrice = ((Price * 12)/100) + Price;
        DefaultTableModel model = (DefaultTableModel) jtable1.getModel();
        model.addRow(new Object[] {"1", "Passion F ", Price, String.format("%.2f", cPrice)});
        ItemCost();

    }//GEN-LAST:event_passionActionPerformed

    private void cranbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cranbActionPerformed
                 double Price = 107.14;
        double cPrice = ((Price * 12)/100) + Price;
        DefaultTableModel model = (DefaultTableModel) jtable1.getModel();
        model.addRow(new Object[] {"1", "Cranberry ", Price, String.format("%.2f", cPrice)});
        ItemCost();

    }//GEN-LAST:event_cranbActionPerformed

    private void mangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mangoActionPerformed
               double Price = 107.14;
        double cPrice = ((Price * 12)/100) + Price;
        DefaultTableModel model = (DefaultTableModel) jtable1.getModel();
        model.addRow(new Object[] {"1", "Mango GT  ", Price, String.format("%.2f", cPrice)});
        ItemCost();

    }//GEN-LAST:event_mangoActionPerformed

    private void strawbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strawbActionPerformed
        double Price = 107.14;
        double cPrice = ((Price * 12)/100) + Price;
        DefaultTableModel model = (DefaultTableModel) jtable1.getModel();
        model.addRow(new Object[] {"1", "StrwberryT", Price, String.format("%.2f", cPrice)});
        ItemCost();

    }//GEN-LAST:event_strawbActionPerformed

    private void melonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_melonActionPerformed
        double Price = 107.14;
        double cPrice = ((Price * 12)/100) + Price;
        DefaultTableModel model = (DefaultTableModel) jtable1.getModel();
        model.addRow(new Object[] {"1", "Melon Tea ", Price, String.format("%.2f", cPrice)});
        ItemCost();

    }//GEN-LAST:event_melonActionPerformed

    private void appleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appleActionPerformed
             double Price = 120.54;
        double cPrice = ((Price * 12)/100) + Price;
        DefaultTableModel model = (DefaultTableModel) jtable1.getModel();
        model.addRow(new Object[] {"1", "Apple Soda", Price, String.format("%.2f", cPrice)});
        ItemCost();

    }//GEN-LAST:event_appleActionPerformed

    private void lemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lemonActionPerformed
              double Price = 120.54;
        double cPrice = ((Price * 12)/100) + Price;
        DefaultTableModel model = (DefaultTableModel) jtable1.getModel();
        model.addRow(new Object[] {"1", "Lemon Soda", Price, String.format("%.2f", cPrice)});
        ItemCost();

    }//GEN-LAST:event_lemonActionPerformed

    private void gappleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gappleActionPerformed
        double Price = 120.54;
        double cPrice = ((Price * 12)/100) + Price;
        DefaultTableModel model = (DefaultTableModel) jtable1.getModel();
        model.addRow(new Object[] {"1", "GreenA Tea", Price, String.format("%.2f", cPrice)});
        ItemCost();

    }//GEN-LAST:event_gappleActionPerformed

    private void orangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orangeActionPerformed
        double Price = 120.54;
        double cPrice = ((Price * 12)/100) + Price;
        DefaultTableModel model = (DefaultTableModel) jtable1.getModel();
        model.addRow(new Object[] {"1", "Orange Tea", Price, String.format("%.2f", cPrice)});
        ItemCost();

    }//GEN-LAST:event_orangeActionPerformed

    private void strawbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strawbsActionPerformed
              double Price = 120.54;
        double cPrice = ((Price * 12)/100) + Price;
        DefaultTableModel model = (DefaultTableModel) jtable1.getModel();
        model.addRow(new Object[] {"1", "StrwberryS", Price, String.format("%.2f", cPrice)});
        ItemCost();

    }//GEN-LAST:event_strawbsActionPerformed

    private void matchalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matchalActionPerformed
        double Price = 142.86;
        double cPrice = ((Price * 12)/100) + Price;
        DefaultTableModel model = (DefaultTableModel) jtable1.getModel();
        model.addRow(new Object[] {"1", "MatchaLtte", Price, String.format("%.2f", cPrice)});
        ItemCost();

    }//GEN-LAST:event_matchalActionPerformed

    private void dmatchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dmatchaActionPerformed
                 double Price = 142.86;
        double cPrice = ((Price * 12)/100) + Price;
        DefaultTableModel model = (DefaultTableModel) jtable1.getModel();
        model.addRow(new Object[] {"1", "Dirty M   ", Price, String.format("%.2f", cPrice)});
        ItemCost();

    }//GEN-LAST:event_dmatchaActionPerformed

    private void vlatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vlatteActionPerformed
                  double Price = 142.86;
        double cPrice = ((Price * 12)/100) + Price;
        DefaultTableModel model = (DefaultTableModel) jtable1.getModel();
        model.addRow(new Object[] {"1", "Vanilla L ", Price, String.format("%.2f", cPrice)});
        ItemCost();

    }//GEN-LAST:event_vlatteActionPerformed

    private void wmochafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wmochafActionPerformed
        double Price = 151.79;
        double cPrice = ((Price * 12)/100) + Price;
        DefaultTableModel model = (DefaultTableModel) jtable1.getModel();
        model.addRow(new Object[] {"1", "WMocha F  ", Price, String.format("%.2f", cPrice)});
        ItemCost();

    }//GEN-LAST:event_wmochafActionPerformed

    private void mochafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mochafActionPerformed
        double Price = 151.79;
        double cPrice = ((Price * 12)/100) + Price;
        DefaultTableModel model = (DefaultTableModel) jtable1.getModel();
        model.addRow(new Object[] {"1", "Mocha F   ", Price, String.format("%.2f", cPrice)});
        ItemCost();

    }//GEN-LAST:event_mochafActionPerformed

    private void bbckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbckActionPerformed
       double Price = 156.25;
        double cPrice = ((Price * 12)/100) + Price;
        DefaultTableModel model = (DefaultTableModel) jtable1.getModel();
        model.addRow(new Object[] {"1", "Blueberry ", Price, String.format("%.2f", cPrice)});
        ItemCost();

    }//GEN-LAST:event_bbckActionPerformed

    private void lvckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lvckActionPerformed
        double Price = 156.25;
        double cPrice = ((Price * 12)/100) + Price;
        DefaultTableModel model = (DefaultTableModel) jtable1.getModel();
        model.addRow(new Object[] {"1", "Lava Cake ", Price, String.format("%.2f", cPrice)});
        ItemCost();

    }//GEN-LAST:event_lvckActionPerformed

    private void upsizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upsizeActionPerformed
        double Price = 17.86;
        double cPrice = ((Price * 12)/100) + Price;
        DefaultTableModel model = (DefaultTableModel) jtable1.getModel();
        model.addRow(new Object[] {"1", "Upsize     ", Price, String.format("%.2f", cPrice)});
        ItemCost();

    }//GEN-LAST:event_upsizeActionPerformed

    private void TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalActionPerformed

    private void TaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TaxActionPerformed

    private void changeDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeDisplayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SubTotal;
    private javax.swing.JTextField Tax;
    private javax.swing.JTextField Total;
    private javax.swing.JButton americano;
    private javax.swing.JButton apple;
    private javax.swing.JTextField barcode;
    private javax.swing.JButton bbck;
    private javax.swing.JButton cappuccino;
    private javax.swing.JButton caramelM;
    private javax.swing.JTextField cashDisplay;
    private javax.swing.JLabel cashLabel;
    private javax.swing.JTextField changeDisplay;
    private javax.swing.JButton clatte;
    private javax.swing.JButton cranb;
    private javax.swing.JLabel date;
    private javax.swing.JButton dmatcha;
    private javax.swing.JButton gapple;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbutton0;
    private javax.swing.JButton jbutton1;
    private javax.swing.JButton jbutton2;
    private javax.swing.JButton jbutton3;
    private javax.swing.JButton jbutton4;
    private javax.swing.JButton jbutton5;
    private javax.swing.JButton jbutton6;
    private javax.swing.JButton jbutton7;
    private javax.swing.JButton jbutton8;
    private javax.swing.JButton jbutton9;
    private javax.swing.JButton jbuttonclear;
    private javax.swing.JButton jbuttonconfirm;
    private javax.swing.JButton jbuttondot;
    private javax.swing.JTable jtable1;
    private javax.swing.JButton lemon;
    private javax.swing.JButton lvck;
    private javax.swing.JButton mango;
    private javax.swing.JButton matchal;
    private javax.swing.JButton melon;
    private javax.swing.JButton mocha;
    private javax.swing.JButton mochaf;
    private javax.swing.JButton orange;
    private javax.swing.JButton passion;
    private javax.swing.JButton printbutton;
    private javax.swing.JButton reset;
    private javax.swing.JButton saltedC;
    private javax.swing.JButton strawb;
    private javax.swing.JButton strawbs;
    private javax.swing.JComboBox<String> tenders;
    private javax.swing.JTextField txtupTotal;
    private javax.swing.JButton upsize;
    private javax.swing.JButton vlatte;
    private javax.swing.JButton voidbutton;
    private javax.swing.JButton wmocha;
    private javax.swing.JButton wmochaf;
    // End of variables declaration//GEN-END:variables
}
